name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - scipy
  - notebook=7
  - jupyterlab
  - jupyter_server
  - pip
  - pip:
      - fastapi
      - fireducks
